/** Suggestion catalogs for profile tag inputs (skills, roles, languages). */

export const PROFILE_SKILL_SUGGESTIONS = [
  "Agile",
  "Scrum",
  "Kanban",
  "Product discovery",
  "User research",
  "Roadmapping",
  "Priorisation",
  "OKR",
  "KPI",
  "A/B testing",
  "Analytics",
  "SQL",
  "Python",
  "Figma",
  "Notion",
  "Jira",
  "Confluence",
  "Mixpanel",
  "Amplitude",
  "Tableau",
  "Looker",
  "Stakeholder management",
  "Facilitation",
  "Workshop",
  "Design thinking",
  "UX writing",
  "API",
  "SaaS",
  "B2B",
  "B2C",
  "Marketplace",
  "Fintech",
  "AI / ML",
  "Prompt engineering",
  "Delivery",
  "Go-to-market",
  "Pricing",
  "Growth",
  "Communication",
  "Leadership",
] as const

export const PROFILE_ROLE_SUGGESTIONS = [
  "Product Owner",
  "Product Manager",
  "Senior Product Manager",
  "Lead Product Manager",
  "Proxy Product Owner",
  "Product Builder",
  "AI Product Manager",
  "Technical Product Manager",
  "Product Marketing Manager",
  "Head of Product",
  "Chief Product Officer",
  "Business Analyst",
  "Delivery Manager",
  "Scrum Master",
  "UX Designer",
  "Product Designer",
  "Engineering Manager",
] as const

export const PROFILE_LANGUAGE_SUGGESTIONS = [
  "Français",
  "Anglais",
  "Espagnol",
  "Allemand",
  "Italien",
  "Portugais",
  "Néerlandais",
  "Chinois",
  "Japonais",
  "Arabe",
  "Russe",
  "Coréen",
] as const

export const PROFILE_LOCATION_EXTRAS = [
  "Remote",
  "Full remote",
  "Hybrid",
  "Île-de-France",
  "Paris",
  "Lyon",
  "Marseille",
  "Toulouse",
  "Bordeaux",
  "Nantes",
  "Lille",
  "Nice",
  "Strasbourg",
  "Rennes",
  "Montpellier",
] as const
