import type {
  AtsKeywordDefinition,
  AtsPriority,
  AtsRoleDefinition,
  AtsRoleImportanceMap,
  AtsSkillType,
} from "@/lib/ats/types"

function kw(
  canonical_name: string,
  category: string,
  options: {
    subcategory?: string
    skill_type?: AtsSkillType
    priority?: AtsPriority
    aliases_fr?: string[]
    aliases_en?: string[]
    ats_weight?: number
    specificity_weight?: number
    description?: string
  } = {}
): AtsKeywordDefinition {
  return {
    canonical_name,
    category,
    subcategory: options.subcategory ?? null,
    skill_type: options.skill_type ?? "hard",
    priority: options.priority ?? "important",
    aliases_fr: options.aliases_fr ?? [],
    aliases_en: options.aliases_en ?? [],
    ats_weight: options.ats_weight ?? 0.5,
    specificity_weight: options.specificity_weight ?? 0.5,
    description: options.description ?? null,
  }
}

/** Expand a flat term list into one keyword row each (canonical = term). */
function terms(
  category: string,
  subcategory: string,
  list: string[],
  defaults: {
    skill_type?: AtsSkillType
    priority?: AtsPriority
    ats_weight?: number
    specificity_weight?: number
  } = {}
): AtsKeywordDefinition[] {
  return list.map((term) =>
    kw(term, category, {
      subcategory,
      skill_type: defaults.skill_type ?? "hard",
      priority: defaults.priority ?? "important",
      ats_weight: defaults.ats_weight,
      specificity_weight: defaults.specificity_weight,
    })
  )
}

/**
 * Product / PO / PM ATS taxonomy (source of truth for seed + offline matching).
 * Synonym groups share one canonical_name; loose lists become individual rows.
 */
export const ATS_KEYWORD_DEFINITIONS: AtsKeywordDefinition[] = [
  // —— Backlog & Requirements ——
  kw("Product Backlog", "backlog_requirements", {
    subcategory: "backlog",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: ["Backlog"],
  }),
  kw("Backlog Management", "backlog_requirements", {
    subcategory: "backlog",
    priority: "critical",
    ats_weight: 0.85,
  }),
  kw("Backlog Prioritization", "backlog_requirements", {
    subcategory: "prioritization",
    priority: "critical",
    ats_weight: 0.9,
    aliases_fr: ["Priorisation du backlog"],
    aliases_en: ["Backlog Priorisation"],
  }),
  kw("Backlog Refinement", "backlog_requirements", {
    subcategory: "backlog",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: ["Grooming", "Refinement", "Backlog Grooming"],
    aliases_fr: ["Raffinement de backlog", "Grooming"],
  }),
  kw("Prioritization", "backlog_requirements", {
    subcategory: "prioritization",
    priority: "critical",
    ats_weight: 0.9,
    aliases_fr: ["Priorisation", "Priority Management"],
    aliases_en: ["Priority Management"],
    description: "Canonical PRIORITIZATION concept",
  }),
  kw("User Stories", "backlog_requirements", {
    subcategory: "requirements",
    priority: "critical",
    ats_weight: 0.9,
    aliases_en: ["User Story", "Stories"],
    aliases_fr: ["User story", "Récits utilisateur"],
  }),
  kw("Technical Stories", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    ats_weight: 0.7,
  }),
  kw("Epics", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_en: ["Epic"],
  }),
  kw("Features", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_en: ["Feature"],
  }),
  kw("Use Cases", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_en: ["Usecases", "Use Case"],
    aliases_fr: ["Cas d'usage", "Cas d’usage"],
  }),
  kw("Requirements", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_fr: ["Exigences", "Besoins"],
  }),
  kw("Business Requirements", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_fr: ["Exigences métier"],
  }),
  kw("Functional Requirements", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_fr: ["Exigences fonctionnelles"],
  }),
  kw("Functional Specifications", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_en: ["Functional Specs"],
    aliases_fr: ["Spécifications fonctionnelles", "Specs fonctionnelles"],
  }),
  kw("Product Requirements", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
  }),
  kw("Specifications", "backlog_requirements", {
    subcategory: "requirements",
    priority: "secondary",
    aliases_fr: ["Spécifications", "Specs"],
  }),
  kw("Acceptance Criteria", "backlog_requirements", {
    subcategory: "requirements",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: ["Acceptance Criterion"],
    aliases_fr: ["Critères d'acceptation", "Critères d’acceptation"],
  }),
  kw("Definition of Done", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_en: ["DoD"],
  }),
  kw("Definition of Ready", "backlog_requirements", {
    subcategory: "requirements",
    priority: "important",
    aliases_en: ["DoR"],
  }),
  kw("Story Mapping", "backlog_requirements", {
    subcategory: "mapping",
    priority: "important",
    aliases_en: ["User Story Mapping"],
  }),
  kw("Impact Mapping", "backlog_requirements", {
    subcategory: "mapping",
    priority: "important",
  }),

  // —— Agile / Scrum ——
  ...terms(
    "agile_scrum",
    "framework",
    [
      "Agile",
      "Agile Methodology",
      "Scrum",
      "Kanban",
      "SAFe",
      "Scaled Agile Framework",
      "Lean",
      "Lean Agile",
    ],
    { priority: "critical", ats_weight: 0.8 }
  ),
  kw("Sprint", "agile_scrum", {
    subcategory: "ceremonies",
    priority: "important",
    aliases_en: ["Sprints"],
  }),
  ...terms(
    "agile_scrum",
    "ceremonies",
    [
      "Sprint Planning",
      "Sprint Review",
      "Sprint Retrospective",
      "Daily Scrum",
      "Release Planning",
      "Capacity Planning",
      "Sprint Goal",
      "Sprint Backlog",
      "Scrum Ceremonies",
      "Agile Ceremonies",
    ],
    { priority: "important" }
  ),
  kw("Daily Stand-up", "agile_scrum", {
    subcategory: "ceremonies",
    priority: "important",
    aliases_en: ["Daily Standup", "Stand-up", "Standup"],
  }),
  kw("Velocity", "agile_scrum", {
    subcategory: "metrics",
    priority: "important",
    skill_type: "metric",
  }),
  kw("Planning Poker", "agile_scrum", {
    subcategory: "estimation",
    priority: "secondary",
  }),
  kw("Story Points", "agile_scrum", {
    subcategory: "estimation",
    priority: "important",
  }),
  ...terms(
    "agile_scrum",
    "practice",
    [
      "Continuous Improvement",
      "Feedback Loop",
      "Iterative Development",
      "Incremental Delivery",
    ],
    { priority: "important" }
  ),

  // —— Prioritization methods ——
  ...terms(
    "prioritization_methods",
    "framework",
    [
      "RICE",
      "MoSCoW",
      "WSJF",
      "Weighted Shortest Job First",
      "Value / Effort",
      "Value Effort Matrix",
      "Impact / Effort",
      "Impact Effort Matrix",
      "Kano Model",
      "Cost of Delay",
      "Opportunity Scoring",
      "ICE Scoring",
      "Business Value",
      "Customer Value",
      "Product Value",
    ],
    { priority: "important", skill_type: "method", ats_weight: 0.7 }
  ),

  // —— Product Management ——
  kw("Product Management", "product_management", {
    subcategory: "core",
    priority: "critical",
    ats_weight: 0.95,
    specificity_weight: 0.4,
    aliases_fr: ["Gestion de produit", "Management produit"],
  }),
  kw("Product Strategy", "product_management", {
    subcategory: "strategy",
    priority: "critical",
    ats_weight: 0.95,
    aliases_fr: ["Stratégie produit"],
  }),
  kw("Product Vision", "product_management", {
    subcategory: "strategy",
    priority: "important",
    aliases_fr: ["Vision produit"],
  }),
  kw("Product Roadmap", "product_management", {
    subcategory: "planning",
    priority: "critical",
    ats_weight: 0.9,
    aliases_en: ["Roadmap", "Roadmap Management"],
    aliases_fr: ["Feuille de route"],
  }),
  ...terms(
    "product_management",
    "core",
    [
      "Product Planning",
      "Product Lifecycle",
      "Product Lifecycle Management",
      "Product Development",
      "Product Ownership",
      "Product Leadership",
      "Product Operations",
      "Product Ops",
      "Product Governance",
      "Portfolio Management",
      "Product Portfolio",
      "Product Initiative",
      "Product Execution",
      "Product Delivery",
      "Product Thinking",
      "Product Sense",
      "Product Culture",
      "Product Excellence",
    ],
    { priority: "important", ats_weight: 0.75 }
  ),

  // —— Discovery ——
  kw("Product Discovery", "discovery", {
    subcategory: "core",
    priority: "critical",
    ats_weight: 0.9,
    aliases_en: ["Discovery"],
    aliases_fr: ["Discovery produit"],
  }),
  ...terms(
    "discovery",
    "core",
    [
      "Continuous Discovery",
      "User Discovery",
      "Discovery Workshop",
      "Discovery Workshops",
      "Customer Discovery",
      "Problem Discovery",
      "Solution Discovery",
      "Problem Validation",
      "Solution Validation",
      "Opportunity Discovery",
      "Opportunity Mapping",
      "Opportunity Solution Tree",
    ],
    { priority: "important", ats_weight: 0.8 }
  ),
  kw("OST", "discovery", {
    subcategory: "core",
    priority: "secondary",
    aliases_en: ["Opportunity Solution Tree"],
    description: "Alias row kept for ATS literal OST",
  }),
  ...terms(
    "discovery",
    "research",
    [
      "Customer Interviews",
      "User Interviews",
      "Stakeholder Interviews",
      "User Research",
      "Customer Research",
      "Qualitative Research",
      "Quantitative Research",
      "Desk Research",
      "Competitive Research",
      "Market Research",
      "Benchmark",
      "Competitive Benchmark",
      "Competitor Analysis",
      "Customer Insights",
      "User Insights",
      "Pain Points",
      "Customer Needs",
      "User Needs",
    ],
    { priority: "important" }
  ),
  kw("Jobs To Be Done", "discovery", {
    subcategory: "framework",
    priority: "important",
    aliases_en: ["JTBD"],
  }),
  kw("Personas", "discovery", {
    subcategory: "artifacts",
    priority: "important",
    aliases_en: ["Proto Personas", "Persona"],
  }),
  kw("User Journey", "discovery", {
    subcategory: "artifacts",
    priority: "important",
    aliases_en: ["Customer Journey", "Journey Mapping", "User Journey Mapping"],
    aliases_fr: ["Parcours utilisateur", "Parcours client"],
  }),

  // —— Experimentation / Growth ——
  kw("A/B Testing", "experimentation_growth", {
    subcategory: "experimentation",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: ["AB Testing", "A/B Test", "Split Testing", "Multivariate Testing"],
    aliases_fr: ["Tests A/B"],
  }),
  ...terms(
    "experimentation_growth",
    "experimentation",
    [
      "Experimentation",
      "Product Experimentation",
      "Hypothesis Testing",
      "Hypothesis",
      "Test and Learn",
    ],
    { priority: "important" }
  ),
  ...terms(
    "experimentation_growth",
    "growth",
    [
      "Growth",
      "Product Growth",
      "Growth Product",
      "Growth Strategy",
      "Growth Loop",
      "Growth Loops",
      "Acquisition",
      "Activation",
      "Retention",
      "Engagement",
      "Conversion",
      "Conversion Rate",
      "Conversion Optimization",
      "Conversion Rate Optimization",
      "CRO",
      "Funnel",
      "Conversion Funnel",
      "Growth Funnel",
      "Funnel Analysis",
      "Funnel Optimization",
      "Onboarding",
      "User Onboarding",
      "Customer Onboarding",
      "Activation Rate",
      "Retention Rate",
      "Churn",
      "Churn Rate",
      "Engagement Rate",
      "Referral",
      "Virality",
      "North Star Metric",
      "Growth Metrics",
    ],
    { priority: "important", ats_weight: 0.75 }
  ),

  // —— Data / Product Analytics ——
  kw("Product Analytics", "data_analytics", {
    subcategory: "core",
    priority: "critical",
    ats_weight: 0.85,
  }),
  ...terms(
    "data_analytics",
    "core",
    [
      "Data Analysis",
      "Data Analytics",
      "Data Driven",
      "Data-Driven",
      "Data-Informed",
      "KPI",
      "KPIs",
      "Key Performance Indicators",
      "Metrics",
      "Product Metrics",
      "Business Metrics",
      "Tracking",
      "Analytics Tracking",
      "Event Tracking",
      "Tracking Plan",
      "Data Tracking",
      "Dashboard",
      "Reporting",
      "Product Dashboard",
      "Adoption Rate",
      "Usage",
      "Adoption",
      "NPS",
      "Net Promoter Score",
      "CSAT",
      "Customer Satisfaction",
      "CES",
      "Customer Effort Score",
      "DAU",
      "WAU",
      "MAU",
      "DAU/MAU",
      "LTV",
      "Lifetime Value",
      "CAC",
      "Customer Acquisition Cost",
      "ARPU",
      "MRR",
      "ARR",
      "Revenue",
      "ROI",
      "Business Impact",
      "Product Impact",
    ],
    { skill_type: "metric", priority: "important" }
  ),

  // —— Delivery ——
  ...terms(
    "delivery",
    "core",
    [
      "Product Delivery",
      "Delivery Management",
      "Release Management",
      "Release Planning",
      "Release",
      "Go Live",
      "Go-Live",
      "Deployment",
      "Production Release",
      "Time-to-Market",
      "Time to Market",
      "Lead Time",
      "Cycle Time",
      "Throughput",
      "Capacity",
      "Burndown Chart",
      "Burnup Chart",
      "Dependencies",
      "Dependency Management",
      "Risk Management",
      "Issue Management",
      "Blocker Management",
      "Scope Management",
      "MVP",
      "Minimum Viable Product",
      "MVP Scoping",
      "Scope",
      "Scoping",
      "Feature Scoping",
      "Increment",
      "Product Increment",
    ],
    { priority: "important", ats_weight: 0.75 }
  ),

  // —— QA / UAT ——
  kw("UAT", "qa_uat", {
    subcategory: "acceptance",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: [
      "User Acceptance Testing",
      "UAT Testing",
      "UAT Campaign",
      "UAT Campaigns",
      "UAT Coordination",
      "Acceptance Testing",
    ],
    aliases_fr: ["Recette", "Recette fonctionnelle", "Recette métier"],
  }),
  kw("QA", "qa_uat", {
    subcategory: "quality",
    priority: "important",
    aliases_en: ["Quality Assurance", "Quality Control"],
  }),
  ...terms(
    "qa_uat",
    "testing",
    [
      "Testing",
      "Functional Testing",
      "Manual Testing",
      "Test Campaign",
      "Test Campaigns",
      "Test Plan",
      "Test Strategy",
      "Test Cases",
      "Test Scenario",
      "Test Scenarios",
      "Acceptance Test",
      "Regression Testing",
      "Non-Regression Testing",
      "Smoke Testing",
      "End-to-End Testing",
      "E2E Testing",
      "Functional Validation",
      "Business Validation",
      "Release Validation",
      "Plan de recette",
      "Cahier de recette",
    ],
    { priority: "important" }
  ),
  ...terms(
    "qa_uat",
    "defects",
    [
      "Anomaly",
      "Anomalies",
      "Bug",
      "Bug Tracking",
      "Bug Management",
      "Bug Prioritization",
      "Defect Management",
      "Bug Rate",
      "Incident",
      "Incident Management",
    ],
    { priority: "important" }
  ),
  kw("Behavior Driven Development", "qa_uat", {
    subcategory: "methods",
    priority: "secondary",
    aliases_en: ["BDD", "Gherkin", "Given When Then"],
    description: "Concept knowledge ≠ Selenium practice",
  }),
  kw("Test Automation", "qa_uat", {
    subcategory: "automation",
    priority: "secondary",
    specificity_weight: 0.85,
    aliases_en: ["Automated Testing", "Selenium"],
    description: "Do not infer practical Selenium experience from concept-only mentions",
  }),

  // —— Stakeholder Management ——
  kw("Stakeholder Management", "stakeholder_management", {
    subcategory: "core",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: [
      "Stakeholders",
      "Stakeholder Engagement",
      "Stakeholder Communication",
      "Stakeholder Alignment",
      "Stakeholder Mapping",
    ],
    aliases_fr: ["Gestion des parties prenantes"],
  }),
  ...terms(
    "stakeholder_management",
    "actors",
    [
      "Business Stakeholders",
      "Executive Stakeholders",
      "Sponsors",
      "Sponsor",
      "Business Owners",
      "Business Owner",
      "Clients",
      "Customers",
      "Users",
      "End Users",
      "Internal Users",
      "External Users",
      "Business Teams",
      "Tech Teams",
      "Cross-functional Teams",
      "Cross-functional Collaboration",
      "Cross-functional Leadership",
      "Collaboration",
      "Alignment",
      "Business Alignment",
      "Product Alignment",
    ],
    { priority: "important", skill_type: "soft" }
  ),

  // —— Management / facilitation ——
  kw("Workshop Facilitation", "management_facilitation", {
    subcategory: "facilitation",
    priority: "critical",
    ats_weight: 0.85,
    aliases_en: ["Facilitation", "Workshop", "Workshops", "Design Workshop", "Product Workshop"],
    aliases_fr: ["Animation d'ateliers", "Animation d’ateliers", "Ateliers"],
  }),
  kw("Coaching", "management_facilitation", {
    subcategory: "coaching",
    priority: "important",
    ats_weight: 0.8,
    aliases_en: ["Product Coaching", "Team Coaching"],
    aliases_fr: ["Coaching produit"],
  }),
  ...terms(
    "management_facilitation",
    "leadership",
    [
      "Mentoring",
      "Mentorship",
      "Leadership",
      "Product Leadership",
      "Leadership d'influence",
      "Influence",
      "Influencing",
      "Decision Making",
      "Problem Solving",
      "Negotiation",
      "Négociation",
      "Communication",
      "Communication Skills",
      "Active Listening",
      "Écoute active",
      "Pedagogy",
      "Pédagogie",
      "Presentation",
      "Presentation Skills",
      "Change Management",
      "Transformation",
      "Digital Transformation",
      "Product Transformation",
    ],
    { skill_type: "soft", priority: "important", ats_weight: 0.55 }
  ),

  // —— UX / UI ——
  ...terms(
    "ux_ui",
    "design",
    [
      "UX",
      "UI",
      "UX/UI",
      "User Experience",
      "User Interface",
      "Product Design",
      "UX Design",
      "UI Design",
      "UX Research",
      "Usability",
      "Usability Testing",
      "User Testing",
      "Prototype",
      "Prototyping",
      "Wireframe",
      "Wireframing",
      "Mockup",
      "Mockups",
      "Design System",
      "Interaction Design",
      "Information Architecture",
      "Design Thinking",
      "Double Diamond",
    ],
    { priority: "important" }
  ),
  kw("Figma", "ux_ui", {
    subcategory: "tools",
    skill_type: "tool",
    priority: "important",
  }),
  kw("Miro", "ux_ui", {
    subcategory: "tools",
    skill_type: "tool",
    priority: "important",
  }),
  kw("Mural", "ux_ui", {
    subcategory: "tools",
    skill_type: "tool",
    priority: "secondary",
  }),

  // —— Technique ——
  ...terms(
    "technical",
    "apis",
    [
      "API",
      "APIs",
      "REST API",
      "REST",
      "RESTful API",
      "GraphQL",
      "Web Services",
      "Webhook",
      "Webhooks",
      "JSON",
      "HTTP",
    ],
    { priority: "important", ats_weight: 0.7 }
  ),
  ...terms(
    "technical",
    "stack",
    [
      "Backend",
      "Frontend",
      "Front-end",
      "Back-end",
      "Web Application",
      "Web App",
      "Mobile Application",
      "Mobile App",
      "iOS",
      "Android",
      "Microservices",
      "Microservice Architecture",
      "Architecture",
      "Technical Architecture",
      "System Architecture",
      "Integration",
      "System Integration",
      "API Integration",
      "Third-party Integration",
      "Technical Specifications",
      "Technical Requirements",
      "Technical Debt",
      "Tech Debt",
      "Legacy",
      "Migration",
      "Data Migration",
      "Technical Constraints",
      "Technical Feasibility",
    ],
    { priority: "important" }
  ),

  // —— Data tools ——
  ...terms(
    "data_tools",
    "sql_db",
    [
      "SQL",
      "Database",
      "Databases",
      "PostgreSQL",
      "MySQL",
      "BigQuery",
      "Snowflake",
      "Data Warehouse",
      "Data Pipeline",
      "ETL",
      "Data Model",
      "Data Modeling",
      "Analytics",
    ],
    { skill_type: "tool", priority: "important" }
  ),
  ...terms(
    "data_tools",
    "product_tools",
    [
      "Google Analytics",
      "GA4",
      "Amplitude",
      "Mixpanel",
      "Hotjar",
      "Looker",
      "Looker Studio",
      "Power BI",
      "Tableau",
      "Metabase",
      "Datadog",
      "Monitoring",
      "Observability",
      "Logs",
    ],
    { skill_type: "tool", priority: "important" }
  ),

  // —— AI Product ——
  kw("Generative AI", "ai_product", {
    subcategory: "core",
    priority: "critical",
    ats_weight: 0.9,
    aliases_en: [
      "GenAI",
      "Generative Artificial Intelligence",
      "Artificial Intelligence",
      "AI",
    ],
    aliases_fr: ["IA Générative", "Intelligence Artificielle", "IA"],
  }),
  ...terms(
    "ai_product",
    "llm",
    [
      "Large Language Model",
      "Large Language Models",
      "LLM",
      "LLMs",
      "GPT",
      "OpenAI",
      "Claude",
      "Gemini",
      "Prompt Engineering",
      "Prompt Design",
      "Prompt Optimization",
    ],
    { priority: "important", ats_weight: 0.8 }
  ),
  ...terms(
    "ai_product",
    "product",
    [
      "AI Product",
      "AI Product Management",
      "AI Product Manager",
      "AI Product Strategy",
      "AI Product Roadmap",
      "AI Features",
      "AI Integration",
      "AI Automation",
      "Workflow Automation",
      "AI Workflow",
      "Agent",
      "AI Agent",
      "AI Agents",
      "Agentic AI",
      "RAG",
      "Retrieval Augmented Generation",
      "Embeddings",
      "Vector Database",
      "Semantic Search",
      "NLP",
      "Natural Language Processing",
      "Machine Learning",
      "ML",
      "Model Evaluation",
      "AI Evaluation",
      "Evaluation Framework",
      "Hallucination",
      "Guardrails",
      "AI Safety",
      "Human in the Loop",
      "HITL",
      "AI Governance",
      "Responsible AI",
      "AI Adoption",
    ],
    { priority: "important" }
  ),

  // —— Automation / Product Builder ——
  ...terms(
    "automation_builder",
    "core",
    [
      "Automation",
      "Process Automation",
      "Business Automation",
      "No-code",
      "No Code",
      "Low-code",
      "Low Code",
      "Product Builder",
      "AI Product Builder",
      "Rapid Prototyping",
      "MVP Development",
      "Rapid Development",
      "AI-Assisted Development",
      "AI Coding",
      "Vibe Coding",
      "API Automation",
      "Webhook Automation",
      "Workflow",
    ],
    { priority: "important", ats_weight: 0.75 }
  ),
  ...terms(
    "automation_builder",
    "tools",
    [
      "Cursor",
      "Lovable",
      "Supabase",
      "Airtable",
      "Make",
      "Make.com",
      "Zapier",
      "n8n",
    ],
    { skill_type: "tool", priority: "important" }
  ),

  // —— SaaS / B2B / B2C ——
  ...terms(
    "saas_business",
    "model",
    [
      "SaaS",
      "Software as a Service",
      "B2B",
      "B2C",
      "B2B2C",
      "Enterprise SaaS",
      "SMB",
      "Enterprise",
      "Platform",
      "Marketplace",
      "Subscription",
      "Subscription Model",
      "Recurring Revenue",
      "Customer Lifecycle",
      "Customer Success",
      "Customer Experience",
      "CX",
      "Self-Service",
      "Product-Led Growth",
      "PLG",
      "Product Led Growth",
      "Freemium",
      "Trial",
      "Free Trial",
      "Expansion",
      "Upsell",
      "Cross-sell",
    ],
    { skill_type: "domain", priority: "important" }
  ),

  // —— CRM ——
  ...terms(
    "crm",
    "core",
    [
      "CRM",
      "Customer Relationship Management",
      "CRM Strategy",
      "CRM Product",
      "Lead Management",
      "Lead Generation",
      "Lead Qualification",
      "Sales Funnel",
      "Marketing Funnel",
      "Pipeline",
      "Sales Pipeline",
      "Customer Data",
      "Customer Database",
      "Segmentation",
      "Customer Segmentation",
      "Lifecycle Marketing",
      "Marketing Automation",
      "Lead Scoring",
      "Customer Support",
      "Support",
      "Ticketing",
      "Helpdesk",
      "Customer Service",
    ],
    { skill_type: "domain", priority: "important" }
  ),

  // —— FinTech / Payments ——
  ...terms(
    "fintech_payments",
    "core",
    [
      "FinTech",
      "Banking",
      "Digital Banking",
      "Online Banking",
      "Retail Banking",
      "Open Banking",
      "Payment",
      "Payments",
      "Payment Processing",
      "Payment Methods",
      "Payment Gateway",
      "Payment Service Provider",
      "PSP",
      "Card Payment",
      "Bank Card",
      "Credit Card",
      "Debit Card",
      "SEPA",
      "Bank Transfer",
      "Wire Transfer",
      "Instant Payment",
      "Recurring Payment",
      "Recurring Billing",
      "Billing",
      "Subscription Billing",
      "Transaction",
      "Transactions",
      "Transaction Monitoring",
      "Fraud",
      "Fraud Detection",
      "Fraud Prevention",
      "Chargeback",
      "Chargebacks",
      "Reconciliation",
      "Payment Reconciliation",
      "Financial Services",
    ],
    { skill_type: "domain", priority: "important", ats_weight: 0.8 }
  ),

  // —— KYC / onboarding ——
  ...terms(
    "kyc_onboarding",
    "compliance",
    [
      "KYC",
      "Know Your Customer",
      "KYB",
      "Know Your Business",
      "AML",
      "Anti-Money Laundering",
      "Compliance",
      "Regulatory Compliance",
      "Identity Verification",
      "ID Verification",
      "Identity Check",
      "Biometric Verification",
      "Biometrics",
      "Document Verification",
      "Document Upload",
      "Document Collection",
      "Customer Verification",
      "Digital Onboarding",
      "Banking Onboarding",
      "Account Opening",
      "Digital Account Opening",
      "E-signature",
      "Electronic Signature",
      "Digital Signature",
      "OTP",
      "One-Time Password",
      "Authentication",
      "Strong Customer Authentication",
      "SCA",
      "PSD2",
      "GDPR",
      "Consent Management",
    ],
    { skill_type: "domain", priority: "important", ats_weight: 0.8 }
  ),

  // —— Insurance ——
  ...terms(
    "insurance",
    "core",
    [
      "Insurance",
      "Assurance",
      "Life Insurance",
      "Assurance Vie",
      "Life Protection",
      "Protection",
      "Insurance Product",
      "Policy",
      "Insurance Policy",
      "Policyholder",
      "Beneficiary",
      "Beneficiaries",
      "Premium",
      "Claim",
      "Claims",
      "Claims Management",
      "Underwriting",
      "Risk Assessment",
      "Insurance Distribution",
      "Insurance Journey",
      "Insurance Subscription",
      "Insurance Onboarding",
      "Life Protection Product",
      "Insurance Regulation",
      "Customer Protection",
    ],
    { skill_type: "domain", priority: "important" }
  ),

  // —— Product tools ——
  ...terms(
    "product_tools",
    "suite",
    [
      "Jira",
      "Confluence",
      "Azure DevOps",
      "ADO",
      "Notion",
      "Linear",
      "Trello",
      "ClickUp",
      "Productboard",
      "Aha!",
      "Slack",
      "Teams",
      "Microsoft Teams",
      "SharePoint",
      "GitHub",
      "GitLab",
      "Google Workspace",
      "Microsoft Office",
      "Excel",
      "PowerPoint",
    ],
    { skill_type: "tool", priority: "important", ats_weight: 0.55 }
  ),

  // —— Certifications ——
  ...terms(
    "certifications",
    "scrum",
    [
      "PSPO",
      "PSPO I",
      "PSPO II",
      "Professional Scrum Product Owner",
      "CSPO",
      "Certified Scrum Product Owner",
      "CSM",
      "Professional Scrum Master",
      "PSM I",
      "SAFe Product Owner",
      "SAFe Product Manager",
      "SAFe POPM",
    ],
    { skill_type: "certification", priority: "secondary", ats_weight: 0.45 }
  ),

  // —— Soft skills (lower ATS weight) ——
  ...terms(
    "soft_skills",
    "traits",
    [
      "Autonomy",
      "Autonomie",
      "Curiosity",
      "Curiosité",
      "Adaptability",
      "Adaptabilité",
      "Organization",
      "Organisation",
      "Rigor",
      "Rigueur",
      "Analytical Thinking",
      "Analytical Skills",
      "Critical Thinking",
      "Teamwork",
      "Empathy",
      "Customer Orientation",
      "User Centricity",
      "User-Centric",
      "Customer Centricity",
      "Ownership",
      "Proactivity",
      "Initiative",
    ],
    { skill_type: "soft", priority: "secondary", ats_weight: 0.35 }
  ),

  // —— Languages ——
  kw("English", "languages", {
    subcategory: "spoken",
    skill_type: "language",
    priority: "important",
    ats_weight: 0.7,
    aliases_fr: ["Anglais", "Anglais professionnel", "Anglais courant"],
    aliases_en: ["Professional English", "Fluent English"],
  }),
  kw("French", "languages", {
    subcategory: "spoken",
    skill_type: "language",
    priority: "secondary",
    ats_weight: 0.5,
    aliases_fr: ["Français"],
  }),
]

export const ATS_ROLE_DEFINITIONS: AtsRoleDefinition[] = [
  {
    role_name: "Product Owner",
    role_family: "product",
    seniority: ["junior", "mid", "senior", "lead"],
  },
  {
    role_name: "Product Manager",
    role_family: "product",
    seniority: ["mid", "senior", "lead", "principal"],
  },
  {
    role_name: "Product Strategist",
    role_family: "product",
    seniority: ["senior", "lead", "principal"],
  },
  {
    role_name: "Product Builder",
    role_family: "product",
    seniority: ["mid", "senior"],
  },
]

/**
 * Explicit role × keyword importance overrides (examples from product brief + sensible defaults).
 * Missing pairs fall back to keyword.ats_weight in seed script.
 */
export const ATS_ROLE_IMPORTANCE: AtsRoleImportanceMap = {
  "Product Owner": {
    "User Stories": 0.95,
    "Product Strategy": 0.55,
    "Product Backlog": 0.95,
    "Backlog Management": 0.95,
    "Backlog Prioritization": 0.95,
    "Backlog Refinement": 0.9,
    "Acceptance Criteria": 0.9,
    "UAT": 0.9,
    Scrum: 0.85,
    "Product Ownership": 0.9,
    "Stakeholder Management": 0.8,
    "Workshop Facilitation": 0.7,
    Coaching: 0.45,
    "Product Discovery": 0.55,
    "Generative AI": 0.35,
    "Product Builder": 0.3,
  },
  "Product Manager": {
    "User Stories": 0.55,
    "Product Strategy": 0.95,
    "Product Management": 0.95,
    "Product Roadmap": 0.9,
    "Product Discovery": 0.9,
    "A/B Testing": 0.8,
    "Product Analytics": 0.85,
    "Stakeholder Management": 0.85,
    Coaching: 0.7,
    "Workshop Facilitation": 0.75,
    "Generative AI": 0.65,
    UAT: 0.5,
    "Product Backlog": 0.55,
  },
  "Product Strategist": {
    "User Stories": 0.25,
    "Product Strategy": 1.0,
    "Product Vision": 0.95,
    "Product Roadmap": 0.9,
    "Product Discovery": 0.85,
    "Product Management": 0.8,
    Coaching: 0.75,
    "Workshop Facilitation": 0.8,
    "Generative AI": 0.7,
    UAT: 0.25,
    "Product Backlog": 0.3,
  },
  "Product Builder": {
    Automation: 0.95,
    "Product Builder": 0.95,
    "Generative AI": 0.9,
    "No-code": 0.85,
    "Low-code": 0.8,
    Prototyping: 0.85,
    "Rapid Prototyping": 0.9,
    Cursor: 0.7,
    Supabase: 0.7,
    "Product Strategy": 0.55,
    "User Stories": 0.4,
    UAT: 0.35,
  },
}
